---
footer: ""
date: "2024-05-07"
title: "An intro to causal inference and its uses in radiotherapy"
subtitle: "ESTRO - Understanding dose-effects: Can we go beyond association - symposium"
---

## {background-image=pngslides/page_001.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_002.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_003.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_004.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_005.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_006.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_007.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_008.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_009.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_010.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_011.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_012.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_013.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_014.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_015.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_016.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_017.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_018.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_019.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_020.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_021.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_022.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_023.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_024.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_025.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_026.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_027.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_028.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_029.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_030.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_031.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_032.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_033.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_034.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_035.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_036.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_037.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_038.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_039.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_040.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_041.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_042.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_043.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_044.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_045.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_046.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_047.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_048.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_049.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_050.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_051.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_052.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_053.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_054.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_055.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_056.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_057.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_058.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_059.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_060.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_061.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_062.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_063.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_064.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_065.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_066.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_067.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_068.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_069.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_070.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_071.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_072.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_073.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_074.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_075.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_076.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_077.png background-size=contain background-repeat=no-repeat}