---
date: "2023-06-24"
title: "My risk model is super accurate so it will be useful for treatment decision making, right? Wrong!"
subtitle: "CHIL 2023 - lightning talk"
---

## {background-image=pngslides/page_001.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_002.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_003.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_004.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_005.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_006.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_007.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_008.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_009.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_010.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_011.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_012.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_013.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_014.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_015.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_016.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_017.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_018.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_019.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_020.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_021.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_022.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_023.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_024.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_025.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_026.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_027.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_028.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_029.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_030.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_031.png background-size=contain background-repeat=no-repeat}
## {background-image=pngslides/page_032.png background-size=contain background-repeat=no-repeat}