project:
  type: website
  resources:
  - CNAME
  #render:
    #- "!talks/240312-dsbiostats-twitter"

website:
  title: "Wouter van Amsterdam"
  description: "Wouter van Amsterdam's academic home page"
  site-url: https://vanamsterdam.github.io
  open-graph: true
  twitter-card:
    site: "@wvanamsterdam"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: Talks
        href: talks.qmd
      - posts.qmd
  google-analytics:
    tracking-id: "G-E4W5XMDCR7"
  page-footer:
    left:
      - "Copyright 2024, Wouter van Amsterdam. All rights reserved."
    right:
      - icon: github
        href: https://github.com/vanamsterdam
      - icon: twitter
        href: https://x.com/wvanamsterdam


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



