project:
  type: website

website:
  title: "Wouter van Amsterdam"
  description: "Wouter van Amsterdam's academic home page"
  site-url: https://vanamsterdam.github.io
  open-graph: true
  twitter-card:
    site: "@wvanamsterdam"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - text: Papers
        href: index.qmd#selected-papers
      - text: Talks
        href: talks.qmd
      - text: Teaching
        href: index.qmd#teaching
      - posts.qmd
      - text: Activities
        href: index.qmd#activities
  google-analytics: "G-E4W5XMDCR7"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



