project:
  type: website

website:
  title: "Wouter van Amsterdam"
  description: "Wouter van Amsterdam's academic home page"
  site-url: https://vanamsterdam.github.io
  open-graph: true
  twitter-card:
    site: "@wvanamsterdam"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
  google-analytics:
    tracking-id: "G-E4W5XMDCR7"
    storage: none

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



