project:
  type: website

website:
  title: "Wouter van Amsterdam"
  open-graph: true
  twitter-card:
    site: "@wvanamsterdam"
  navbar:
    background: light
    search: false
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



